parameters:
- name: environment
  type: string
  default: Development
- name: pool
  type: string
  default: labeltool
- name: kubernetesServiceConnection
  type: string
  default: aks-dev-dns-bf01fb7b.hcp.chinaeast2.cx.prod.service.azk8s.cn
- name: namespace
  type: string
  default: cocktail-development
- name: chartPath
  type: string
  default: Deployment/Helm/cocktail
- name: releaseName
  type: string
  default: cocktail-development
- name: valueFile
  type: string
  default: Deployment/Helm/cocktail/values.development.yaml
- name: chartName
  type: string
  default: ''
- name: stageNamePostfix
  type: string
  default: ''

stages:
- stage: ${{ parameters.environment }}${{ parameters.stageNamePostfix }}
  jobs:
  - deployment: ${{ parameters.environment }}
    environment: ${{ parameters.environment }}
    pool:
      vmImage: ubuntu-20.04
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - template: helm-init.yaml
          - template: helm-upgrade.yaml
            parameters:
              kubernetesServiceConnection: ${{ parameters.kubernetesServiceConnection }}
              namespace: ${{ parameters.namespace }}
              chartPath: ${{ parameters.chartPath }}
              releaseName: ${{ parameters.releaseName }}
              valueFile: ${{ parameters.valueFile }}
              chartName: ${{ parameters.chartName }}