kind: Namespace
apiVersion: v1
metadata:
  name: labeltool

---

kind: Service
apiVersion: v1
metadata:
  name: mongodb5
  namespace: labeltool
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

---

kind: Endpoints
apiVersion: v1
metadata:
  name: mongodb5
  namespace: labeltool
subsets:
  - addresses:
      - ip: 10.244.220.5
    ports:
      - port: 27017

---

kind: Service
apiVersion: v1
metadata:
  name: mongodb6
  namespace: labeltool
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

---

kind: Endpoints
apiVersion: v1
metadata:
  name: mongodb6
  namespace: labeltool
subsets:
  - addresses:
      - ip: 10.244.220.6
    ports:
      - port: 27017

---

kind: Service
apiVersion: v1
metadata:
  name: mongodb7
  namespace: labeltool
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

---

kind: Endpoints
apiVersion: v1
metadata:
  name: mongodb7
  namespace: labeltool
subsets:
  - addresses:
      - ip: 10.244.220.7
    ports:
      - port: 27017

---

kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: labeltool
spec:
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200

---

kind: Endpoints
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: labeltool
subsets:
  - addresses:
      - ip: 10.244.220.11
    ports:
      - port: 9200

---

kind: ConfigMap  
apiVersion: v1  
metadata:  
  name: appsettings 
  namespace: labeltool
  labels:
    app: webapi
data:  
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Debug",
          "System": "Information",
          "Microsoft": "Information"
        }
      },
      "AllowedHosts": "*",
      "MongoDB": {
        "ConnectionString": "mongodb://mongodb5:27017,mongodb6:27017,mongodb7:27017",
        "Database": "labeltool"
      },
      "StorageTypes": {
        "GridFS": true,
        "S3": false
      },
      "LoggingTypes": {
        "Serilog": true
      },
      "Serilog": {
        "WriteTo": [
          {
            "Name": "Elasticsearch",
            "Args": {
              "nodeUris": "http://elasticsearch:9200",
              "indexFormat": "labeltool{0:yyyy.MM}",
              "minimumLogEventLevel": "Verbose",
              "autoRegisterTemplate": true
            }
          }
        ]
      },
      "User": {
        "TokenExpiredInDays": 7,
        "MaxExistingValidLoginsPerUser": 256,
        "Issuer": "labeltool",
        "Audience": "labeltool"
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  namespace: labeltool
spec:
  selector:
    matchLabels:
      app: webapi
  replicas: 1
  template:
    metadata:
      labels:
        app: webapi
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - micro-faq-3
                - micro-faq-4
                - micro-faq-6
                - micro-faq-7
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - micro-faq-6
      containers:
      - name: webapi
        image: 10.244.220.9:5000/musickg.webapi:v1.0.1
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:5000"
        volumeMounts:
        - name: appsettings
          readOnly: true
          mountPath: /MusicKG.WebApi/appsettings.json
          subPath: appsettings.json
        readinessProbe:
          httpGet:
            path: /index.html
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /index.html
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 30
      volumes:
      - name: appsettings
        configMap:
          name: appsettings

---

kind: Service
apiVersion: v1
metadata:
  name: webapi
  namespace: labeltool
spec:
  selector:
    app: webapi
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 30900

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: labeltool
spec:
  selector:
    matchLabels:
      app: webui
  replicas: 1
  template:
    metadata:
      labels:
        app: webui
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - micro-faq-3
                - micro-faq-4
                - micro-faq-6
                - micro-faq-7
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - micro-faq-3
      containers:
      - name: webui
        image: 10.244.220.9:5000/musickg.webui:v1.0.3
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 30

---

kind: Service
apiVersion: v1
metadata:
  name: webui
  namespace: labeltool
spec:
  selector:
    app: webui
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30901