kind: Namespace
apiVersion: v1
metadata:
  name: musickg-dev
  labels:
    name: musickg-dev

---

kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: musickg-dev
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

---

kind: Endpoints
apiVersion: v1
metadata:
  name: mongodb
  namespace: musickg-dev
subsets:
  - addresses:
      - ip: 10.1.4.5
    ports:
      - port: 27017

---

kind: Service
apiVersion: v1
metadata:
  name: ceph
  namespace: musickg-dev
spec:
  type: ExternalName
  externalName: d2kdemo.eastasia.cloudapp.azure.com

---

kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: musickg-dev
spec:
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200

---

kind: Endpoints
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: musickg-dev
subsets:
  - addresses:
      - ip: 10.1.4.5
    ports:
      - port: 9200

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  namespace: musickg-dev
spec:
  selector:
    matchLabels:
      app: webapi
  replicas: 1
  template:
    metadata:
      labels:
        app: webapi
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - labeltool
                - cmcclabel-qa
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - labeltool
      containers:
      - name: webapi
        image: labeltool.eastasia.cloudapp.azure.com:5443/musickg.webapi:latest
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:5000"
        readinessProbe:
          httpGet:
            path: /index.html
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /index.html
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 30
      imagePullSecrets:
      - name: labeltool

---

kind: Service
apiVersion: v1
metadata:
  name: webapi
  namespace: musickg-dev
spec:
  selector:
    app: webapi
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 30000

---

kind: ConfigMap  
apiVersion: v1  
metadata:  
  name: nginx 
  namespace: musickg-dev
  labels:
    app: webui
data:  
  nginx.conf: |
    server {
      listen       80;
      server_name  localhost;

      server_tokens off;

      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        
        try_files $uri $uri/ /index.html;
      }

      location /api/ {
        client_max_body_size 0;
        proxy_pass http://webapi:5000;
      }

      location /api/faq/ {
        client_max_body_size 0;
        rewrite ^/api/faq/(.*) /api/$1 break;
        proxy_pass http://webapi.faq-dev:5000;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: musickg-dev
spec:
  selector:
    matchLabels:
      app: webui
  replicas: 1
  template:
    metadata:
      labels:
        app: webui
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - labeltool
                - cmcclabel-qa
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - labeltool
      containers:
      - name: webui
        image: labeltool.eastasia.cloudapp.azure.com:5443/musickg.webui:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx
          readOnly: true
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 30
      imagePullSecrets:
      - name: labeltool
      volumes:
      - name: nginx
        configMap:
          name: nginx

---

kind: Service
apiVersion: v1
metadata:
  name: webui
  namespace: musickg-dev
spec:
  selector:
    app: webui
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kepreprocessor
  namespace: musickg-dev
spec:
  selector:
    matchLabels:
      app: kepreprocessor
  replicas: 1
  template:
    metadata:
      labels:
        app: kepreprocessor
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - labeltool
                - cmcclabel-qa
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - labeltool
      containers:
      - name: kepreprocessor
        image: labeltool.eastasia.cloudapp.azure.com:5443/musickg.kepreprocessor:latest
        ports:
        - containerPort: 5002
      imagePullSecrets:
      - name: labeltool

---

kind: Service
apiVersion: v1
metadata:
  name: kepreprocessor
  namespace: musickg-dev
spec:
  selector:
    app: kepreprocessor
  type: NodePort
  ports:
  - protocol: TCP
    port: 5002
    nodePort: 30002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphdataingestion
  namespace: musickg-dev
spec:
  selector:
    matchLabels:
      app: graphdataingestion
  replicas: 1
  template:
    metadata:
      labels:
        app: graphdataingestion
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - labeltool
                - cmcclabel-qa
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - labeltool
      containers:
      - name: graphdataingestion
        image: labeltool.eastasia.cloudapp.azure.com:5443/musickg.graphdataingestion:latest
        ports:
        - containerPort: 8800
        env:
        - name: TZ
          value: "UTC"
        - name: MUSICKG_ENVIRONMENT
          value: "prod"
      imagePullSecrets:
      - name: labeltool

---

kind: Service
apiVersion: v1
metadata:
  name: graphdataingestion
  namespace: musickg-dev
spec:
  selector:
    app: graphdataingestion
  type: NodePort
  ports:
  - protocol: TCP
    port: 8800
    nodePort: 30003

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow
  namespace: musickg-dev
spec:
  selector:
    matchLabels:
      app: workflow
  replicas: 1
  template:
    metadata:
      labels:
        app: workflow
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - labeltool
                - cmcclabel-qa
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - labeltool
      containers:
      - name: workflow
        image: labeltool.eastasia.cloudapp.azure.com:5443/musickg.workflow:latest
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:5000"
      imagePullSecrets:
      - name: labeltool

---

kind: Service
apiVersion: v1
metadata:
  name: workflow
  namespace: musickg-dev
spec:
  selector:
    app: workflow
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 30004