variables:
  solution: 'API/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

trigger:
  branches:
    include:
    - master
    - honda_dev
    - refs/tags/honda_v*
  paths:
    include:
    - GraphPortal/MusicKG.WebUi/*
    - Deployment/Piplines/MusicKG.WebUI.yaml
    - Deployment/Piplines/templates/*.yaml
    - Deployment/Piplines/templates/angular/*

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: labeltool
    steps:
    - template: templates/angular/angular-init.yaml
      parameters:
        nodejsVersion: 11.x
    - template: templates/angular/angular-test.yaml
      parameters:
        workingDir: GraphPortal/MusicKG.WebUi
    - template: templates/angular/angular-build.yaml
      parameters:
        workingDir: GraphPortal/MusicKG.WebUi
    - template: templates/docker-build.yaml
      parameters:
        dockerfile: GraphPortal/MusicKG.WebUi/Dockerfile
        registry: labeltool.eastasia.cloudapp.azure.com:5443
        repository: musickg.webui