trigger: none

variables:
  solution: 'API/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

pool:
  name: labeltool

steps:
- template: templates/dotnet/dotnet-init.yaml
  parameters:
    dotnetVersion: 5.0.x
- template: templates/dotnet/dotnet-restore.yaml
  parameters:
    projects: GraphPortal/HondaPlugins/MusicKG.HondaPlugins.VehicleFault.Rest/*.csproj
- template: templates/dotnet/dotnet-build.yaml
  parameters:
    projects: GraphPortal/HondaPlugins/MusicKG.HondaPlugins.VehicleFault.Rest/*.csproj