variables:
  solution: 'API/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

trigger:
  branches:
    include:
    - master
    - honda_dev
    - refs/tags/honda_v*
  paths:
    include:
    - GraphPortal/DataManager/*
    - GraphPortal/MusicKG.WebApi.ClientWrapper/*
    - GraphPortal/MusicKG.WebApi.Contract/*
    - GraphPortal/MusicKG.DataAccess/*
    - GraphPortal/MusicKG.Tensorflow.Wrapper/*
    - GraphPortal/MusicKG.Utility/*
    - Scheduler/*
    - GraphPortal/HondaPlugins/*
    - Deployment/Pipeline/MusicKG.HondaPlugins.OfflineWorker.yaml
    - Deployment/Pipeline/templates/*.yaml
    - Deployment/Pipeline/templates/dotnet/*
    exclude:
    - Scheduler/MusicKG.Scheduler.Example/*
    - GraphPortal/HondaPlugins/MusicKG.HondaPlugins.VehicleFault.Rest/*
    - GraphPortal/HondaPlugins/Scripts/*
    - GraphPortal/DataManager/MusicKG.DataManager.ModelTrainingWorker/*
    - GraphPortal/DataManager/MusicKG.DataManager.ModelTrainer/*
    - Deployment/Pipeline/templates/dotnet/dotnet-pack.yaml
    - Deployment/Pipeline/templates/dotnet/dotnet-push.yaml

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: labeltool
    steps:
    - template: templates/dotnet/dotnet-init.yaml
      parameters:
        dotnetVersion: 5.0.x
    - template: templates/dotnet/dotnet-restore.yaml
      parameters:
        projects: GraphPortal/HondaPlugins/MusicKG.HondaPlugins.OfflineWorker/*.csproj
    - template: templates/dotnet/dotnet-publish.yaml
      parameters:
        projects: GraphPortal/HondaPlugins/MusicKG.HondaPlugins.OfflineWorker/*.csproj
    - template: templates/docker-build.yaml
      parameters:
        dockerfile: GraphPortal/HondaPlugins/MusicKG.HondaPlugins.OfflineWorker/Dockerfile
        registry: labeltool.eastasia.cloudapp.azure.com:5443
        repository: honda.offlineworker