//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicKG.HondaPlugins.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AIRiskLevelSource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AIRiskLevelSource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicKG.HondaPlugins.DataAccess.Resources.AIRiskLevelSource", typeof(AIRiskLevelSource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了.
        /// </summary>
        public static string 完了 {
            get {
                return ResourceManager.GetString("完了", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已对策.
        /// </summary>
        public static string 已对策 {
            get {
                return ResourceManager.GetString("已对策", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已明确.
        /// </summary>
        public static string 已明确 {
            get {
                return ResourceManager.GetString("已明确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 推进中.
        /// </summary>
        public static string 推进中 {
            get {
                return ResourceManager.GetString("推进中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无需对策.
        /// </summary>
        public static string 无需 {
            get {
                return ResourceManager.GetString("无需", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无需对策.
        /// </summary>
        public static string 无需对策 {
            get {
                return ResourceManager.GetString("无需对策", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未明确.
        /// </summary>
        public static string 未明确 {
            get {
                return ResourceManager.GetString("未明确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未立项.
        /// </summary>
        public static string 未立项 {
            get {
                return ResourceManager.GetString("未立项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 监视.
        /// </summary>
        public static string 监视 {
            get {
                return ResourceManager.GetString("监视", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空白.
        /// </summary>
        public static string 空白 {
            get {
                return ResourceManager.GetString("空白", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需再次立项.
        /// </summary>
        public static string 需再立项 {
            get {
                return ResourceManager.GetString("需再立项", resourceCulture);
            }
        }
    }
}
