//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicKG.HondaPlugins.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AIRiskLevelSource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AIRiskLevelSource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicKG.HondaPlugins.DataAccess.Resources.AIRiskLevelSource", typeof(AIRiskLevelSource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 完了 的本地化字符串。
        /// </summary>
        public static string 完了 {
            get {
                return ResourceManager.GetString("完了", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已对策 的本地化字符串。
        /// </summary>
        public static string 已对策 {
            get {
                return ResourceManager.GetString("已对策", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已明确 的本地化字符串。
        /// </summary>
        public static string 已明确 {
            get {
                return ResourceManager.GetString("已明确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推进中 的本地化字符串。
        /// </summary>
        public static string 推进中 {
            get {
                return ResourceManager.GetString("推进中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无需对策 的本地化字符串。
        /// </summary>
        public static string 无需 {
            get {
                return ResourceManager.GetString("无需", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未明确 的本地化字符串。
        /// </summary>
        public static string 未明确 {
            get {
                return ResourceManager.GetString("未明确", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未立项 的本地化字符串。
        /// </summary>
        public static string 未立项 {
            get {
                return ResourceManager.GetString("未立项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监视 的本地化字符串。
        /// </summary>
        public static string 监视 {
            get {
                return ResourceManager.GetString("监视", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空白 的本地化字符串。
        /// </summary>
        public static string 空白 {
            get {
                return ResourceManager.GetString("空白", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需再次立项 的本地化字符串。
        /// </summary>
        public static string 需再立项 {
            get {
                return ResourceManager.GetString("需再立项", resourceCulture);
            }
        }
    }
}
