//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicKG.HondaPlugins.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Columns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Columns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicKG.HondaPlugins.DataAccess.Resources.Columns", typeof(Columns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总局转发投诉.
        /// </summary>
        public static string GOV {
            get {
                return ResourceManager.GetString("GOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800.
        /// </summary>
        public static string HOTLINE {
            get {
                return ResourceManager.GetString("HOTLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部主题.
        /// </summary>
        public static string HOTLINE_ALL_TOPIC {
            get {
                return ResourceManager.GetString("HOTLINE_ALL_TOPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 城市.
        /// </summary>
        public static string HOTLINE_CITY {
            get {
                return ResourceManager.GetString("HOTLINE_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分类.
        /// </summary>
        public static string HOTLINE_CLASSIFY_NAME {
            get {
                return ResourceManager.GetString("HOTLINE_CLASSIFY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟进记录.
        /// </summary>
        public static string HOTLINE_COMM_RECORD {
            get {
                return ResourceManager.GetString("HOTLINE_COMM_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户意见.
        /// </summary>
        public static string HOTLINE_CUSTOMER_DESC {
            get {
                return ResourceManager.GetString("HOTLINE_CUSTOMER_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特约店.
        /// </summary>
        public static string HOTLINE_DEALER_CD {
            get {
                return ResourceManager.GetString("HOTLINE_DEALER_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排放标准.
        /// </summary>
        public static string HOTLINE_EMISSION_STANDARD {
            get {
                return ResourceManager.GetString("HOTLINE_EMISSION_STANDARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车架号.
        /// </summary>
        public static string HOTLINE_FRAME_NO {
            get {
                return ResourceManager.GetString("HOTLINE_FRAME_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行驶里程.
        /// </summary>
        public static string HOTLINE_MILEAGE {
            get {
                return ResourceManager.GetString("HOTLINE_MILEAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车型.
        /// </summary>
        public static string HOTLINE_MODEL_CD {
            get {
                return ResourceManager.GetString("HOTLINE_MODEL_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建时间.
        /// </summary>
        public static string HOTLINE_OPEN_TIME {
            get {
                return ResourceManager.GetString("HOTLINE_OPEN_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 省份.
        /// </summary>
        public static string HOTLINE_PROVINCE {
            get {
                return ResourceManager.GetString("HOTLINE_PROVINCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 片区.
        /// </summary>
        public static string HOTLINE_REGION {
            get {
                return ResourceManager.GetString("HOTLINE_REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特约店简称.
        /// </summary>
        public static string HOTLINE_SHORTNAME {
            get {
                return ResourceManager.GetString("HOTLINE_SHORTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工单编号.
        /// </summary>
        public static string HOTLINE_SR_NUM {
            get {
                return ResourceManager.GetString("HOTLINE_SR_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 级别.
        /// </summary>
        public static string HOTLINE_SR_SEVERITY {
            get {
                return ResourceManager.GetString("HOTLINE_SR_SEVERITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步时间.
        /// </summary>
        public static string HOTLINE_Timestamp {
            get {
                return ResourceManager.GetString("HOTLINE_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车种名称.
        /// </summary>
        public static string HOTLINE_TPTYPE_NAME {
            get {
                return ResourceManager.GetString("HOTLINE_TPTYPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年款.
        /// </summary>
        public static string HOTLINE_YEAR_TYPE {
            get {
                return ResourceManager.GetString("HOTLINE_YEAR_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 媒体（总表）.
        /// </summary>
        public static string MEDIA_MAIN {
            get {
                return ResourceManager.GetString("MEDIA_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 媒体（附表）.
        /// </summary>
        public static string MEDIA_SUB {
            get {
                return ResourceManager.GetString("MEDIA_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQI.
        /// </summary>
        public static string MQI {
            get {
                return ResourceManager.GetString("MQI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车款.
        /// </summary>
        public static string MQI_CAR_MODEL {
            get {
                return ResourceManager.GetString("MQI_CAR_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车型.
        /// </summary>
        public static string MQI_CAR_TYPE {
            get {
                return ResourceManager.GetString("MQI_CAR_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属城市.
        /// </summary>
        public static string MQI_CITY {
            get {
                return ResourceManager.GetString("MQI_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总修理费用.
        /// </summary>
        public static string MQI_COST_REPAIR {
            get {
                return ResourceManager.GetString("MQI_COST_REPAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特约店名称.
        /// </summary>
        public static string MQI_DEALER_CD {
            get {
                return ResourceManager.GetString("MQI_DEALER_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 故障日期.
        /// </summary>
        public static string MQI_FAULT_DATE {
            get {
                return ResourceManager.GetString("MQI_FAULT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车架号码.
        /// </summary>
        public static string MQI_FRAME_NO {
            get {
                return ResourceManager.GetString("MQI_FRAME_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购买日期.
        /// </summary>
        public static string MQI_INITIAL_REGIST_DATE {
            get {
                return ResourceManager.GetString("MQI_INITIAL_REGIST_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 诊断结果.
        /// </summary>
        public static string MQI_MAINTENANCE_PROCESS {
            get {
                return ResourceManager.GetString("MQI_MAINTENANCE_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 里程数.
        /// </summary>
        public static string MQI_MILE_AGE {
            get {
                return ResourceManager.GetString("MQI_MILE_AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年款.
        /// </summary>
        public static string MQI_MODEL_YEAR {
            get {
                return ResourceManager.GetString("MQI_MODEL_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQI编号.
        /// </summary>
        public static string MQI_MQI_NO {
            get {
                return ResourceManager.GetString("MQI_MQI_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用天数.
        /// </summary>
        public static string MQI_NUMBER_DAYS {
            get {
                return ResourceManager.GetString("MQI_NUMBER_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主零件中文名.
        /// </summary>
        public static string MQI_PART_NAME {
            get {
                return ResourceManager.GetString("MQI_PART_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主零件号.
        /// </summary>
        public static string MQI_PART_NO {
            get {
                return ResourceManager.GetString("MQI_PART_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生产日期.
        /// </summary>
        public static string MQI_PRODUCTION_DATE {
            get {
                return ResourceManager.GetString("MQI_PRODUCTION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属省份.
        /// </summary>
        public static string MQI_PROVINCE {
            get {
                return ResourceManager.GetString("MQI_PROVINCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 故障原因代码.
        /// </summary>
        public static string MQI_REASON_CD {
            get {
                return ResourceManager.GetString("MQI_REASON_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 故障原因.
        /// </summary>
        public static string MQI_REASON_DESC {
            get {
                return ResourceManager.GetString("MQI_REASON_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属片区.
        /// </summary>
        public static string MQI_REGION {
            get {
                return ResourceManager.GetString("MQI_REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题.
        /// </summary>
        public static string MQI_SUBJECT {
            get {
                return ResourceManager.GetString("MQI_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 问诊内容.
        /// </summary>
        public static string MQI_SYMPTOM_DESC {
            get {
                return ResourceManager.GetString("MQI_SYMPTOM_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步时间.
        /// </summary>
        public static string MQI_Timestamp {
            get {
                return ResourceManager.GetString("MQI_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技术咨询.
        /// </summary>
        public static string TECH_CONSULTING {
            get {
                return ResourceManager.GetString("TECH_CONSULTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 厂家回答.
        /// </summary>
        public static string TECH_CONSULTING_AUDIT_OPINION {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_AUDIT_OPINION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车型.
        /// </summary>
        public static string TECH_CONSULTING_CAR_TYPE {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_CAR_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车型名.
        /// </summary>
        public static string TECH_CONSULTING_CAR_TYPE_NAME {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_CAR_TYPE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 咨询时间.
        /// </summary>
        public static string TECH_CONSULTING_CONSULTATION_DATE {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_CONSULTATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特约店.
        /// </summary>
        public static string TECH_CONSULTING_DEALER_CD {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_DEALER_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 故障日期.
        /// </summary>
        public static string TECH_CONSULTING_FAULT_DATE {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_FAULT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车身号.
        /// </summary>
        public static string TECH_CONSULTING_FRAME_NO {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_FRAME_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 维修过程.
        /// </summary>
        public static string TECH_CONSULTING_MAINTENANCE_PROCESS {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_MAINTENANCE_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 维修方案.
        /// </summary>
        public static string TECH_CONSULTING_MAINTENANCE_PROGRAM {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_MAINTENANCE_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 里程.
        /// </summary>
        public static string TECH_CONSULTING_MILE_AGE {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_MILE_AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生产日期.
        /// </summary>
        public static string TECH_CONSULTING_PRODUCTION_DATE {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_PRODUCTION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 级别.
        /// </summary>
        public static string TECH_CONSULTING_RANK {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_RANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购买日期.
        /// </summary>
        public static string TECH_CONSULTING_SHIPPING_DATE {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_SHIPPING_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 具体现象.
        /// </summary>
        public static string TECH_CONSULTING_SPECIFIC_PHENOMENON {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_SPECIFIC_PHENOMENON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题.
        /// </summary>
        public static string TECH_CONSULTING_SUBJECT {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顾客描述.
        /// </summary>
        public static string TECH_CONSULTING_SYMPTOM_DESC {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_SYMPTOM_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同步时间.
        /// </summary>
        public static string TECH_CONSULTING_Timestamp {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制号.
        /// </summary>
        public static string TECH_CONSULTING_WR_NO {
            get {
                return ResourceManager.GetString("TECH_CONSULTING_WR_NO", resourceCulture);
            }
        }
    }
}
