//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicKG.HondaPlugins.DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProvinceSource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProvinceSource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicKG.HondaPlugins.DataAccess.Resources.ProvinceSource", typeof(ProvinceSource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 上海 的本地化字符串。
        /// </summary>
        public static string 上海市 {
            get {
                return ResourceManager.GetString("上海市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 云南 的本地化字符串。
        /// </summary>
        public static string 云南省 {
            get {
                return ResourceManager.GetString("云南省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内蒙古 的本地化字符串。
        /// </summary>
        public static string 内蒙古自治区 {
            get {
                return ResourceManager.GetString("内蒙古自治区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 北京 的本地化字符串。
        /// </summary>
        public static string 北京市 {
            get {
                return ResourceManager.GetString("北京市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 台湾 的本地化字符串。
        /// </summary>
        public static string 台湾省 {
            get {
                return ResourceManager.GetString("台湾省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吉林 的本地化字符串。
        /// </summary>
        public static string 吉林省 {
            get {
                return ResourceManager.GetString("吉林省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 四川 的本地化字符串。
        /// </summary>
        public static string 四川省 {
            get {
                return ResourceManager.GetString("四川省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天津 的本地化字符串。
        /// </summary>
        public static string 天津市 {
            get {
                return ResourceManager.GetString("天津市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宁夏 的本地化字符串。
        /// </summary>
        public static string 宁夏回族自治区 {
            get {
                return ResourceManager.GetString("宁夏回族自治区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安徽 的本地化字符串。
        /// </summary>
        public static string 安徽省 {
            get {
                return ResourceManager.GetString("安徽省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 山东 的本地化字符串。
        /// </summary>
        public static string 山东省 {
            get {
                return ResourceManager.GetString("山东省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 山西 的本地化字符串。
        /// </summary>
        public static string 山西省 {
            get {
                return ResourceManager.GetString("山西省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广东 的本地化字符串。
        /// </summary>
        public static string 广东省 {
            get {
                return ResourceManager.GetString("广东省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广西 的本地化字符串。
        /// </summary>
        public static string 广西壮族自治区 {
            get {
                return ResourceManager.GetString("广西壮族自治区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新疆 的本地化字符串。
        /// </summary>
        public static string 新疆维吾尔自治区 {
            get {
                return ResourceManager.GetString("新疆维吾尔自治区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 江苏 的本地化字符串。
        /// </summary>
        public static string 江苏省 {
            get {
                return ResourceManager.GetString("江苏省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 江西 的本地化字符串。
        /// </summary>
        public static string 江西省 {
            get {
                return ResourceManager.GetString("江西省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 河北 的本地化字符串。
        /// </summary>
        public static string 河北省 {
            get {
                return ResourceManager.GetString("河北省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 河南 的本地化字符串。
        /// </summary>
        public static string 河南省 {
            get {
                return ResourceManager.GetString("河南省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浙江 的本地化字符串。
        /// </summary>
        public static string 浙江省 {
            get {
                return ResourceManager.GetString("浙江省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海南 的本地化字符串。
        /// </summary>
        public static string 海南省 {
            get {
                return ResourceManager.GetString("海南省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 湖北 的本地化字符串。
        /// </summary>
        public static string 湖北省 {
            get {
                return ResourceManager.GetString("湖北省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 湖南 的本地化字符串。
        /// </summary>
        public static string 湖南省 {
            get {
                return ResourceManager.GetString("湖南省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 甘肃 的本地化字符串。
        /// </summary>
        public static string 甘肃省 {
            get {
                return ResourceManager.GetString("甘肃省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 福建 的本地化字符串。
        /// </summary>
        public static string 福建省 {
            get {
                return ResourceManager.GetString("福建省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 西藏 的本地化字符串。
        /// </summary>
        public static string 西藏自治区 {
            get {
                return ResourceManager.GetString("西藏自治区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贵州 的本地化字符串。
        /// </summary>
        public static string 贵州省 {
            get {
                return ResourceManager.GetString("贵州省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 辽宁 的本地化字符串。
        /// </summary>
        public static string 辽宁省 {
            get {
                return ResourceManager.GetString("辽宁省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重庆 的本地化字符串。
        /// </summary>
        public static string 重庆市 {
            get {
                return ResourceManager.GetString("重庆市", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 陕西 的本地化字符串。
        /// </summary>
        public static string 陕西省 {
            get {
                return ResourceManager.GetString("陕西省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 青海 的本地化字符串。
        /// </summary>
        public static string 青海省 {
            get {
                return ResourceManager.GetString("青海省", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑龙江 的本地化字符串。
        /// </summary>
        public static string 黑龙江省 {
            get {
                return ResourceManager.GetString("黑龙江省", resourceCulture);
            }
        }
    }
}
