//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicKG.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MusicKGMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MusicKGMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicKG.Service.Resources.MusicKGMessages", typeof(MusicKGMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update auto task creation rules..
        /// </summary>
        public static string AuotTaskCreationRulesUpdateFailedMessage {
            get {
                return ResourceManager.GetString("AuotTaskCreationRulesUpdateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization header is missing..
        /// </summary>
        public static string AuthHeaderMissingMessage {
            get {
                return ResourceManager.GetString("AuthHeaderMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authorization header..
        /// </summary>
        public static string AuthHeaderWrongMessage {
            get {
                return ResourceManager.GetString("AuthHeaderWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to authorize user..
        /// </summary>
        public static string AuthUserFailedMessage {
            get {
                return ResourceManager.GetString("AuthUserFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoTaskCreationRule does not exsit..
        /// </summary>
        public static string AutoTaskCreationRuleNotExistsMessage {
            get {
                return ResourceManager.GetString("AutoTaskCreationRuleNotExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearer error=&quot;{0}&quot;.
        /// </summary>
        public static string BearerErrorMessage {
            get {
                return ResourceManager.GetString("BearerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default rule must not have any docuement tag..
        /// </summary>
        public static string DefaultRuleMustNotContainAnyTag {
            get {
                return ResourceManager.GetString("DefaultRuleMustNotContainAnyTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialize json file to object failed..
        /// </summary>
        public static string DeserializeJsonFileFailedMessage {
            get {
                return ResourceManager.GetString("DeserializeJsonFileFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology entity file only can be uploaded once..
        /// </summary>
        public static string DialogOntologyEntityDuplicateMessage {
            get {
                return ResourceManager.GetString("DialogOntologyEntityDuplicateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology intent file only can be uploaded once..
        /// </summary>
        public static string DialogOntologyIntentDuplicateMessage {
            get {
                return ResourceManager.GetString("DialogOntologyIntentDuplicateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew dialog ontology failed..
        /// </summary>
        public static string DialogOntologyRenewFailedMessage {
            get {
                return ResourceManager.GetString("DialogOntologyRenewFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create dictionary..
        /// </summary>
        public static string DictionaryCreateFailedMessage {
            get {
                return ResourceManager.GetString("DictionaryCreateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete dictionary..
        /// </summary>
        public static string DictionaryDeleteFailedMessage {
            get {
                return ResourceManager.GetString("DictionaryDeleteFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity can not be empty..
        /// </summary>
        public static string DictionaryEntityEmptyMessage {
            get {
                return ResourceManager.GetString("DictionaryEntityEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary entries can not be empty..
        /// </summary>
        public static string DictionaryEntriesEmptyMessage {
            get {
                return ResourceManager.GetString("DictionaryEntriesEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary name can not be empty..
        /// </summary>
        public static string DictionaryNameEmtpyMessage {
            get {
                return ResourceManager.GetString("DictionaryNameEmtpyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary name already exist..
        /// </summary>
        public static string DictionaryNameExistMessage {
            get {
                return ResourceManager.GetString("DictionaryNameExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary does not exist..
        /// </summary>
        public static string DictionaryNotExistMessage {
            get {
                return ResourceManager.GetString("DictionaryNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update dictionary..
        /// </summary>
        public static string DictionaryUpdateFailedMessage {
            get {
                return ResourceManager.GetString("DictionaryUpdateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different rules cannot have same tag..
        /// </summary>
        public static string DifferentRulesCannotHaveSameTagMessage {
            get {
                return ResourceManager.GetString("DifferentRulesCannotHaveSameTagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of document item count must equals to the number of documents..
        /// </summary>
        public static string DocumentItemCountWrongMessage {
            get {
                return ResourceManager.GetString("DocumentItemCountWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name cannot be empty..
        /// </summary>
        public static string DocumentNameEmptyMessage {
            get {
                return ResourceManager.GetString("DocumentNameEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document does not exist..
        /// </summary>
        public static string DocumentNotExistMessage {
            get {
                return ResourceManager.GetString("DocumentNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileName: {0}, reason: {1}..
        /// </summary>
        public static string DocumentUploadFailedDetailMessage {
            get {
                return ResourceManager.GetString("DocumentUploadFailedDetailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are errors when uploading documents, total uploading count: {0}, failed document count: {1}. Details: .
        /// </summary>
        public static string DocumentUploadFailedMessage {
            get {
                return ResourceManager.GetString("DocumentUploadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File content does not exist..
        /// </summary>
        public static string FileContentNotExistMessage {
            get {
                return ResourceManager.GetString("FileContentNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file content..
        /// </summary>
        public static string FileContentWrongMessage {
            get {
                return ResourceManager.GetString("FileContentWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file format..
        /// </summary>
        public static string FileFormatWrongMessage {
            get {
                return ResourceManager.GetString("FileFormatWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date is greater or equal than to date..
        /// </summary>
        public static string FromDateGreaterThanToDateMessage {
            get {
                return ResourceManager.GetString("FromDateGreaterThanToDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get file content..
        /// </summary>
        public static string GetFileContentFailedMessage {
            get {
                return ResourceManager.GetString("GetFileContentFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create honda syndrome..
        /// </summary>
        public static string HondaSyndromeCreateFailedMessage {
            get {
                return ResourceManager.GetString("HondaSyndromeCreateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honda syndrome name can not be empty..
        /// </summary>
        public static string HondaSyndromeNameEmtpyMessage {
            get {
                return ResourceManager.GetString("HondaSyndromeNameEmtpyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honda syndrome does not exisst..
        /// </summary>
        public static string HondaSyndromeNotExistMessage {
            get {
                return ResourceManager.GetString("HondaSyndromeNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update honda syndrome..
        /// </summary>
        public static string HondaSyndromeUpdateFailedMessage {
            get {
                return ResourceManager.GetString("HondaSyndromeUpdateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preannotation Processor class {0} must implement IProcessorProvider..
        /// </summary>
        public static string InvalidPreannotationProcessor {
            get {
                return ResourceManager.GetString("InvalidPreannotationProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing categories..
        /// </summary>
        public static string MissingCategoriesMessage {
            get {
                return ResourceManager.GetString("MissingCategoriesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default rule for task creation must not be empty..
        /// </summary>
        public static string MustHaveDefaultRuleForTaskCreation {
            get {
                return ResourceManager.GetString("MustHaveDefaultRuleForTaskCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-default rules must have tags..
        /// </summary>
        public static string NonDefaultRulesMustHaveTags {
            get {
                return ResourceManager.GetString("NonDefaultRulesMustHaveTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag or tag value does not exist..
        /// </summary>
        public static string NoTagValueCanBeUpdatedMessage {
            get {
                return ResourceManager.GetString("NoTagValueCanBeUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task does not exist or task can not be approved..
        /// </summary>
        public static string NoTaskCanBeApprovedMessage {
            get {
                return ResourceManager.GetString("NoTaskCanBeApprovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task does not exist or task can not be rejected..
        /// </summary>
        public static string NoTaskCanBeRejectMessage {
            get {
                return ResourceManager.GetString("NoTaskCanBeRejectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only task with status ConflictResolved can be merged..
        /// </summary>
        public static string OnlyConflictResolvedStatusCanbeMerged {
            get {
                return ResourceManager.GetString("OnlyConflictResolvedStatusCanbeMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity and relation annotation..
        /// </summary>
        public static string OntologyEntityAndRelationGuidlineMessage {
            get {
                return ResourceManager.GetString("OntologyEntityAndRelationGuidlineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create ontology entity..
        /// </summary>
        public static string OntologyEntityCreateFailedMessage {
            get {
                return ResourceManager.GetString("OntologyEntityCreateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate property names in ontology entity..
        /// </summary>
        public static string OntologyEntityDuplicatePropertyNameMessage {
            get {
                return ResourceManager.GetString("OntologyEntityDuplicatePropertyNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology entity name is empty..
        /// </summary>
        public static string OntologyEntityNameEmptyMessage {
            get {
                return ResourceManager.GetString("OntologyEntityNameEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology entity name already exist..
        /// </summary>
        public static string OntologyEntityNameExistMessage {
            get {
                return ResourceManager.GetString("OntologyEntityNameExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology entity does not exist..
        /// </summary>
        public static string OntologyEntityNotExistMessage {
            get {
                return ResourceManager.GetString("OntologyEntityNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology entity property contains invalid characters..
        /// </summary>
        public static string OntologyEntityPropertyNameWrongMessage {
            get {
                return ResourceManager.GetString("OntologyEntityPropertyNameWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update ontology entity..
        /// </summary>
        public static string OntologyEntityUpdateFailedMessage {
            get {
                return ResourceManager.GetString("OntologyEntityUpdateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create ontology relation..
        /// </summary>
        public static string OntologyRelationCreateFailedMessage {
            get {
                return ResourceManager.GetString("OntologyRelationCreateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate property names in ontology relation..
        /// </summary>
        public static string OntologyRelationDuplicatePropertyNameMessage {
            get {
                return ResourceManager.GetString("OntologyRelationDuplicatePropertyNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first entity Id format error..
        /// </summary>
        public static string OntologyRelationFirstEntityIdWrongMessage {
            get {
                return ResourceManager.GetString("OntologyRelationFirstEntityIdWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first entity in the ontology relation does not exist..
        /// </summary>
        public static string OntologyRelationFirstEntityNotExistMessage {
            get {
                return ResourceManager.GetString("OntologyRelationFirstEntityNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology relation name is empty..
        /// </summary>
        public static string OntologyRelationNameEmptyMessage {
            get {
                return ResourceManager.GetString("OntologyRelationNameEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology relation name already exist..
        /// </summary>
        public static string OntologyRelationNameExistMessage {
            get {
                return ResourceManager.GetString("OntologyRelationNameExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology relation name contains invalid characters..
        /// </summary>
        public static string OntologyRelationNameWrongMessage {
            get {
                return ResourceManager.GetString("OntologyRelationNameWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology relation does not exist..
        /// </summary>
        public static string OntologyRelationNotExistMessage {
            get {
                return ResourceManager.GetString("OntologyRelationNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology relation property contains invalid characters..
        /// </summary>
        public static string OntologyRelationPropertyNameWrongMessage {
            get {
                return ResourceManager.GetString("OntologyRelationPropertyNameWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second entity Id format error..
        /// </summary>
        public static string OntologyRelationSecondEntityIdWrongMessage {
            get {
                return ResourceManager.GetString("OntologyRelationSecondEntityIdWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second entity in the ontology relation does not exist..
        /// </summary>
        public static string OntologyRelationSecondEntityNotExistMessage {
            get {
                return ResourceManager.GetString("OntologyRelationSecondEntityNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update ontology relation..
        /// </summary>
        public static string OntologyRelationUpdateFailedMessage {
            get {
                return ResourceManager.GetString("OntologyRelationUpdateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate ontology entity names exist in the file..
        /// </summary>
        public static string OntologyUploadDuplicateEntityNameMessage {
            get {
                return ResourceManager.GetString("OntologyUploadDuplicateEntityNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate ontology relation names exist in the file..
        /// </summary>
        public static string OntologyUploadDuplicateRelationNameMessage {
            get {
                return ResourceManager.GetString("OntologyUploadDuplicateRelationNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace Id cannot be empty..
        /// </summary>
        public static string OntologyWorkspaceIdEmptyMessage {
            get {
                return ResourceManager.GetString("OntologyWorkspaceIdEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace Id format is incorrect..
        /// </summary>
        public static string OntologyWorkspaceIdWrongMessage {
            get {
                return ResourceManager.GetString("OntologyWorkspaceIdWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse token..
        /// </summary>
        public static string ParseTokenFailedMessage {
            get {
                return ResourceManager.GetString("ParseTokenFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preannotation processor assembly {0} is not found..
        /// </summary>
        public static string PreannotationAssemblyNotFound {
            get {
                return ResourceManager.GetString("PreannotationAssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preannotation processor class {0} is not found..
        /// </summary>
        public static string PreannotationClassNotFound {
            get {
                return ResourceManager.GetString("PreannotationClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityId can not be empty..
        /// </summary>
        public static string RuleEntityIdEmptyMessage {
            get {
                return ResourceManager.GetString("RuleEntityIdEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule name can not be empty..
        /// </summary>
        public static string RuleNameEmptyMessage {
            get {
                return ResourceManager.GetString("RuleNameEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule name already exist..
        /// </summary>
        public static string RuleNameExistMessage {
            get {
                return ResourceManager.GetString("RuleNameExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule does not exist..
        /// </summary>
        public static string RuleNotExistMessage {
            get {
                return ResourceManager.GetString("RuleNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regexs can not be empty..
        /// </summary>
        public static string RuleRegexsEmptyMessage {
            get {
                return ResourceManager.GetString("RuleRegexsEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid scheme..
        /// </summary>
        public static string SchemaWrongMessage {
            get {
                return ResourceManager.GetString("SchemaWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is unavailable..
        /// </summary>
        public static string SystemDownMessage {
            get {
                return ResourceManager.GetString("SystemDownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag value does not exist..
        /// </summary>
        public static string TagValueNotExistMessage {
            get {
                return ResourceManager.GetString("TagValueNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotator or document does not exist..
        /// </summary>
        public static string TaskAnnotatorOrDocumentNotExistMessage {
            get {
                return ResourceManager.GetString("TaskAnnotatorOrDocumentNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create task..
        /// </summary>
        public static string TaskCreateFailedMessage {
            get {
                return ResourceManager.GetString("TaskCreateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task expected due at should be greater than the current time..
        /// </summary>
        public static string TaskExpectedDueAtWrongMessage {
            get {
                return ResourceManager.GetString("TaskExpectedDueAtWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task name can not be empty..
        /// </summary>
        public static string TaskNameEmptyMessage {
            get {
                return ResourceManager.GetString("TaskNameEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task name already exist..
        /// </summary>
        public static string TaskNameExistMessage {
            get {
                return ResourceManager.GetString("TaskNameExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task does not exist..
        /// </summary>
        public static string TaskNotExistMessage {
            get {
                return ResourceManager.GetString("TaskNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task overlap not in range..
        /// </summary>
        public static string TaskOverlapWrongMessage {
            get {
                return ResourceManager.GetString("TaskOverlapWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown task status..
        /// </summary>
        public static string TaskStatusUnknownMessage {
            get {
                return ResourceManager.GetString("TaskStatusUnknownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update task..
        /// </summary>
        public static string TaskUpdateFailedMessage {
            get {
                return ResourceManager.GetString("TaskUpdateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category for the given document, first item is the whole document, others are the paragraph of this document..
        /// </summary>
        public static string TextClassifyGuidlineMessage {
            get {
                return ResourceManager.GetString("TextClassifyGuidlineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a given user question (source text) and standard question (target text), indicate whether they are similar..
        /// </summary>
        public static string TextSimilarityGuidlineMessage {
            get {
                return ResourceManager.GetString("TextSimilarityGuidlineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokenization process failed, details: {0}..
        /// </summary>
        public static string TokenizationProcessFailed {
            get {
                return ResourceManager.GetString("TokenizationProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        public static string TokenWrongMessage {
            get {
                return ResourceManager.GetString("TokenWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized operation..
        /// </summary>
        public static string UnauthorizedMessage {
            get {
                return ResourceManager.GetString("UnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create user..
        /// </summary>
        public static string UserCreateFailedMessage {
            get {
                return ResourceManager.GetString("UserCreateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is disabled..
        /// </summary>
        public static string UserDisabledMessage {
            get {
                return ResourceManager.GetString("UserDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalide user ID..
        /// </summary>
        public static string UserIdWrongMessage {
            get {
                return ResourceManager.GetString("UserIdWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many logins for this user..
        /// </summary>
        public static string UserLoginCountOverflowMessage {
            get {
                return ResourceManager.GetString("UserLoginCountOverflowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name can not be empty..
        /// </summary>
        public static string UserNameEmptyMessage {
            get {
                return ResourceManager.GetString("UserNameEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exist..
        /// </summary>
        public static string UserNameExistMessage {
            get {
                return ResourceManager.GetString("UserNameExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong user name or password..
        /// </summary>
        public static string UserNamePasswordWrongMessage {
            get {
                return ResourceManager.GetString("UserNamePasswordWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist..
        /// </summary>
        public static string UserNotExistMessage {
            get {
                return ResourceManager.GetString("UserNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can not be empty..
        /// </summary>
        public static string UserPasswordEmptyMessage {
            get {
                return ResourceManager.GetString("UserPasswordEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token or unauthorized access..
        /// </summary>
        public static string UserUnauthorizedMessage {
            get {
                return ResourceManager.GetString("UserUnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag already exists..
        /// </summary>
        public static string ValueAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("ValueAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get workflow step..
        /// </summary>
        public static string WorkflowStepGetFailedMessage {
            get {
                return ResourceManager.GetString("WorkflowStepGetFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create workspace..
        /// </summary>
        public static string WorkspaceCreateFailedMessage {
            get {
                return ResourceManager.GetString("WorkspaceCreateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete workspace..
        /// </summary>
        public static string WorkspaceDeleteFailedMessage {
            get {
                return ResourceManager.GetString("WorkspaceDeleteFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace name can not be empty..
        /// </summary>
        public static string WorkspaceNameEmptyMessage {
            get {
                return ResourceManager.GetString("WorkspaceNameEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace name already exist..
        /// </summary>
        public static string WorkspaceNameExistMessage {
            get {
                return ResourceManager.GetString("WorkspaceNameExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace does not exist..
        /// </summary>
        public static string WorkspaceNotExistMessage {
            get {
                return ResourceManager.GetString("WorkspaceNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace type name can not be empty..
        /// </summary>
        public static string WorkspaceTypeNameEmptyMessage {
            get {
                return ResourceManager.GetString("WorkspaceTypeNameEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace type name already exist..
        /// </summary>
        public static string WorkspaceTypeNameExistMessage {
            get {
                return ResourceManager.GetString("WorkspaceTypeNameExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace type does not exist..
        /// </summary>
        public static string WorkspaceTypeNotExistMessage {
            get {
                return ResourceManager.GetString("WorkspaceTypeNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update workspace..
        /// </summary>
        public static string WorkspaceUpdateFailedMessage {
            get {
                return ResourceManager.GetString("WorkspaceUpdateFailedMessage", resourceCulture);
            }
        }
    }
}
