//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicKG.HondaPlugins.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MusicKGHondaPluginsMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MusicKGHondaPluginsMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicKG.HondaPlugins.Services.Resources.MusicKGHondaPluginsMessage", typeof(MusicKGHondaPluginsMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization header is missing..
        /// </summary>
        public static string AuthHeaderMissingMessage {
            get {
                return ResourceManager.GetString("AuthHeaderMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authorization header..
        /// </summary>
        public static string AuthHeaderWrongMessage {
            get {
                return ResourceManager.GetString("AuthHeaderWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to authorize user..
        /// </summary>
        public static string AuthUserFailedMessage {
            get {
                return ResourceManager.GetString("AuthUserFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearer error=&quot;{0}&quot;.
        /// </summary>
        public static string BearerErrorMessage {
            get {
                return ResourceManager.GetString("BearerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The carType cannot be null or white space..
        /// </summary>
        public static string CarTypeCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("CarTypeCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm record cannot be null..
        /// </summary>
        public static string ConfirmRecordCannotBeNull {
            get {
                return ResourceManager.GetString("ConfirmRecordCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only data source &apos;GOV&apos;. &apos;Media&apos; can be imported from excel file..
        /// </summary>
        public static string DataSourceMustTranlsatedFromMariaDB {
            get {
                return ResourceManager.GetString("DataSourceMustTranlsatedFromMariaDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceed overall max query days..
        /// </summary>
        public static string ExceedOverallMaxDays {
            get {
                return ResourceManager.GetString("ExceedOverallMaxDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceed overall max query month..
        /// </summary>
        public static string ExceedOverallMaxMonth {
            get {
                return ResourceManager.GetString("ExceedOverallMaxMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceed overall max query week..
        /// </summary>
        public static string ExceedOverallMaxWeek {
            get {
                return ResourceManager.GetString("ExceedOverallMaxWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault date must in 90 days..
        /// </summary>
        public static string FaultDateMustInThreeMonth {
            get {
                return ResourceManager.GetString("FaultDateMustInThreeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File for &apos;{0}&apos; must have valid feature &apos;{1}&apos;, line: {2}..
        /// </summary>
        public static string FeatureNotFoundMessage {
            get {
                return ResourceManager.GetString("FeatureNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the honda syndrome..
        /// </summary>
        public static string HondaSyndromeCreateFailedMessage {
            get {
                return ResourceManager.GetString("HondaSyndromeCreateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honda syndrome name can not be empty..
        /// </summary>
        public static string HondaSyndromeNameEmtpyMessage {
            get {
                return ResourceManager.GetString("HondaSyndromeNameEmtpyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honda syndrome does not exisst..
        /// </summary>
        public static string HondaSyndromeNotExistMessage {
            get {
                return ResourceManager.GetString("HondaSyndromeNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the honda syndrome..
        /// </summary>
        public static string HondaSyndromeUpdateFailedMessage {
            get {
                return ResourceManager.GetString("HondaSyndromeUpdateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored vehicle data already exists..
        /// </summary>
        public static string IgnoredVehicleAlreadyExists {
            get {
                return ResourceManager.GetString("IgnoredVehicleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored vehicle data does not exist..
        /// </summary>
        public static string IgnoredVehicleNotExists {
            get {
                return ResourceManager.GetString("IgnoredVehicleNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File for &apos;{0}&apos; must have at least one non-empty feature &apos;{1}&apos;..
        /// </summary>
        public static string KeyFeatureNotFoundMessage {
            get {
                return ResourceManager.GetString("KeyFeatureNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The param month format is wrong..
        /// </summary>
        public static string MonthFormatIsWrong {
            get {
                return ResourceManager.GetString("MonthFormatIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No related qis info..
        /// </summary>
        public static string NoRelatedQisInfo {
            get {
                return ResourceManager.GetString("NoRelatedQisInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to params can not be null or totally empty..
        /// </summary>
        public static string ParamsCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ParamsCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse token..
        /// </summary>
        public static string ParseTokenFailedMessage {
            get {
                return ResourceManager.GetString("ParseTokenFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part name cannot be empty..
        /// </summary>
        public static string PartNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("PartNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QICNo is invalid..
        /// </summary>
        public static string QICNoIsInvalid {
            get {
                return ResourceManager.GetString("QICNoIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QIS info cannot be found..
        /// </summary>
        public static string QISInfoCannotBeFound {
            get {
                return ResourceManager.GetString("QISInfoCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawId cannot be empty..
        /// </summary>
        public static string RawIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("RawIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw id does not exist..
        /// </summary>
        public static string RawIdNotExists {
            get {
                return ResourceManager.GetString("RawIdNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data reannotation task does not exist..
        /// </summary>
        public static string ReannotationTaskDoesNotExist {
            get {
                return ResourceManager.GetString("ReannotationTaskDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reannotation task fault time span is overlap..
        /// </summary>
        public static string ReannotationTaskFaultTimeSpanOverlap {
            get {
                return ResourceManager.GetString("ReannotationTaskFaultTimeSpanOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid scheme..
        /// </summary>
        public static string SchemaWrongMessage {
            get {
                return ResourceManager.GetString("SchemaWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time must be less than end time..
        /// </summary>
        public static string StartTimeMustBeLessThanEndTime {
            get {
                return ResourceManager.GetString("StartTimeMustBeLessThanEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syndrome cannot be empty..
        /// </summary>
        public static string SyndromeCannotBeEmpty {
            get {
                return ResourceManager.GetString("SyndromeCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syndrome does not exist..
        /// </summary>
        public static string SyndromeNotExists {
            get {
                return ResourceManager.GetString("SyndromeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokenization process failed, details: {0}..
        /// </summary>
        public static string TokenizationProcessFailed {
            get {
                return ResourceManager.GetString("TokenizationProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        public static string TokenWrongMessage {
            get {
                return ResourceManager.GetString("TokenWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized operation..
        /// </summary>
        public static string UnauthorizedMessage {
            get {
                return ResourceManager.GetString("UnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update vehicle fault data failed..
        /// </summary>
        public static string UpdateVehicleFaultFailed {
            get {
                return ResourceManager.GetString("UpdateVehicleFaultFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token or unauthorized access..
        /// </summary>
        public static string UserUnauthorizedMessage {
            get {
                return ResourceManager.GetString("UserUnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle fault  QIS info to update can not be null or totally empty.
        /// </summary>
        public static string VehicleFaultQISInfoToUpdateCannotBeNull {
            get {
                return ResourceManager.GetString("VehicleFaultQISInfoToUpdateCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning record cannot be found..
        /// </summary>
        public static string WarningRecordCannotBeFound {
            get {
                return ResourceManager.GetString("WarningRecordCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the warning record confirm message.
        /// </summary>
        public static string WarningRecordConfirmUpdateFailed {
            get {
                return ResourceManager.GetString("WarningRecordConfirmUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save a warning record..
        /// </summary>
        public static string WarningRecordCreateFailed {
            get {
                return ResourceManager.GetString("WarningRecordCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild to update MatchedFrequency flag..
        /// </summary>
        public static string WarningRecordMatchFrequencyUpdateFailed {
            get {
                return ResourceManager.GetString("WarningRecordMatchFrequencyUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create warning task..
        /// </summary>
        public static string WarningTaskCreateFailed {
            get {
                return ResourceManager.GetString("WarningTaskCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the warning task..
        /// </summary>
        public static string WarningTaskDeleteFailed {
            get {
                return ResourceManager.GetString("WarningTaskDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create warning task detail..
        /// </summary>
        public static string WarningTaskDetailCreateFailed {
            get {
                return ResourceManager.GetString("WarningTaskDetailCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the warning task detail..
        /// </summary>
        public static string WarningTaskDetailUpdateFailed {
            get {
                return ResourceManager.GetString("WarningTaskDetailUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The warning task does not exist..
        /// </summary>
        public static string WarningTaskDoesNotExist {
            get {
                return ResourceManager.GetString("WarningTaskDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning task name already exists..
        /// </summary>
        public static string WarningTaskNameAlreadyExists {
            get {
                return ResourceManager.GetString("WarningTaskNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the warning task..
        /// </summary>
        public static string WarningTaskUpdateFailed {
            get {
                return ResourceManager.GetString("WarningTaskUpdateFailed", resourceCulture);
            }
        }
    }
}
