//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicKG.WebApi.Contract.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayNameResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNameResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicKG.WebApi.Contract.Resources.DisplayNameResources", typeof(DisplayNameResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptro id list.
        /// </summary>
        public static string AcceptorIds {
            get {
                return ResourceManager.GetString("AcceptorIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotator ID list.
        /// </summary>
        public static string AnnotatorIDlist {
            get {
                return ResourceManager.GetString("AnnotatorIDlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto task creation rules.
        /// </summary>
        public static string AutoTaskCreationRules {
            get {
                return ResourceManager.GetString("AutoTaskCreationRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary id list.
        /// </summary>
        public static string DictionaryIDlist {
            get {
                return ResourceManager.GetString("DictionaryIDlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary name.
        /// </summary>
        public static string DictionaryName {
            get {
                return ResourceManager.GetString("DictionaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document count per one task.
        /// </summary>
        public static string DocumentCount {
            get {
                return ResourceManager.GetString("DocumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document ID list.
        /// </summary>
        public static string DocumentIDlist {
            get {
                return ResourceManager.GetString("DocumentIDlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name.
        /// </summary>
        public static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document status.
        /// </summary>
        public static string DocumentStatus {
            get {
                return ResourceManager.GetString("DocumentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document tags.
        /// </summary>
        public static string DocumentTags {
            get {
                return ResourceManager.GetString("DocumentTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Due At.
        /// </summary>
        public static string ExpectedDueAt {
            get {
                return ResourceManager.GetString("ExpectedDueAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First entity Id.
        /// </summary>
        public static string FirstEntityId {
            get {
                return ResourceManager.GetString("FirstEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honda syndrome Name.
        /// </summary>
        public static string HondaSyndromeName {
            get {
                return ResourceManager.GetString("HondaSyndromeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspector User Id list.
        /// </summary>
        public static string InspectorIds {
            get {
                return ResourceManager.GetString("InspectorIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is annotation result automatically approved.
        /// </summary>
        public static string Isannotationresultautomaticallyapproved {
            get {
                return ResourceManager.GetString("Isannotationresultautomaticallyapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If automatically merge annotation result.
        /// </summary>
        public static string IsAutoMerging {
            get {
                return ResourceManager.GetString("IsAutoMerging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is knowledge automatically merged.
        /// </summary>
        public static string Isknowledgeautomaticallymerged {
            get {
                return ResourceManager.GetString("Isknowledgeautomaticallymerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max finish days for a task.
        /// </summary>
        public static string MaxFinishDays {
            get {
                return ResourceManager.GetString("MaxFinishDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology entity description.
        /// </summary>
        public static string OntologyEntityDescription {
            get {
                return ResourceManager.GetString("OntologyEntityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology entity ID.
        /// </summary>
        public static string OntologyEntityId {
            get {
                return ResourceManager.GetString("OntologyEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology entity mark color.
        /// </summary>
        public static string OntologyEntityMarkColor {
            get {
                return ResourceManager.GetString("OntologyEntityMarkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology entity name.
        /// </summary>
        public static string OntologyEntityName {
            get {
                return ResourceManager.GetString("OntologyEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology property description.
        /// </summary>
        public static string OntologyPropertyDescription {
            get {
                return ResourceManager.GetString("OntologyPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology property name.
        /// </summary>
        public static string OntologyPropertyName {
            get {
                return ResourceManager.GetString("OntologyPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology property type.
        /// </summary>
        public static string OntologyPropertyType {
            get {
                return ResourceManager.GetString("OntologyPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology relation description.
        /// </summary>
        public static string OntologyRelationDescription {
            get {
                return ResourceManager.GetString("OntologyRelationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontology relation name.
        /// </summary>
        public static string OntologyRelationName {
            get {
                return ResourceManager.GetString("OntologyRelationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlap.
        /// </summary>
        public static string Overlap {
            get {
                return ResourceManager.GetString("Overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadOnly Users.
        /// </summary>
        public static string ReadOnlyUserIds {
            get {
                return ResourceManager.GetString("ReadOnlyUserIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expressions.
        /// </summary>
        public static string RegularExpressions {
            get {
                return ResourceManager.GetString("RegularExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule name.
        /// </summary>
        public static string RuleName {
            get {
                return ResourceManager.GetString("RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second entity Id.
        /// </summary>
        public static string SecondEntityId {
            get {
                return ResourceManager.GetString("SecondEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag color.
        /// </summary>
        public static string TagColor {
            get {
                return ResourceManager.GetString("TagColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag description.
        /// </summary>
        public static string TagDescription {
            get {
                return ResourceManager.GetString("TagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag value.
        /// </summary>
        public static string TagValue {
            get {
                return ResourceManager.GetString("TagValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto task creation user id.
        /// </summary>
        public static string TaskCreationUser {
            get {
                return ResourceManager.GetString("TaskCreationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task document result.
        /// </summary>
        public static string Taskdocumentresult {
            get {
                return ResourceManager.GetString("Taskdocumentresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task document result type.
        /// </summary>
        public static string Taskdocumentresulttype {
            get {
                return ResourceManager.GetString("Taskdocumentresulttype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task document status.
        /// </summary>
        public static string Taskdocumentstatus {
            get {
                return ResourceManager.GetString("Taskdocumentstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task name.
        /// </summary>
        public static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task type.
        /// </summary>
        public static string TaskType {
            get {
                return ResourceManager.GetString("TaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles.
        /// </summary>
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User status.
        /// </summary>
        public static string UserStatus {
            get {
                return ResourceManager.GetString("UserStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocabularies.
        /// </summary>
        public static string Vocabularies {
            get {
                return ResourceManager.GetString("Vocabularies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace description.
        /// </summary>
        public static string WorkspaceDescription {
            get {
                return ResourceManager.GetString("WorkspaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace name.
        /// </summary>
        public static string WorkspaceName {
            get {
                return ResourceManager.GetString("WorkspaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace type Id.
        /// </summary>
        public static string WorkspaceTypeId {
            get {
                return ResourceManager.GetString("WorkspaceTypeId", resourceCulture);
            }
        }
    }
}
